### ISSUE TITLE
how i to ues the code???

### ISSUE THREAD

**Issue by hytxx** [rockchip-linux/camera_engine_rkisp#1]
anything else description for this code ???

**Comment by JulesThuillier** [comment]
How long does it take to write a README ?

**Comment by ayaromenok** [comment]
> How long does it take to write a README ?
Humans don't live so long ;) Looks like it's most up-to-date rkispv(while other repos don't use it as submodule and include some hardcoded versions), but still not manage to make it work. Probably, need to going back via release number :)

**Comment by JulesThuillier** [comment]
Just for your informations, here are some changes I had to do to build that code on a Nano Pi m4.
Edit **productConfigs.mk line 16**
`CROSS_COMPILE ?= /usr/bin/`

Then just compiled with
`sudo make ARCH=arm`

The libraries build in **build/lib** but I couldn't build the following libraries : 
- librkisp_aiq.so
- librkisp_ae.so
- librkisp_awb.so

that should apparently be build if we refer to the commented part in file **install**

**Comment by journey175** [comment]
I did not see any code version update,and there are not any description for these code。
I can turn to whom when I meet some problems.

**Comment by JeffyCN** [comment]
i gave up reading the code long time ago :(

but lucky it's not hard to just use it.

what we need is to install the iq files and the generated(or prebuilt) isp libraries and a rkisp_3A_server binary, then write a simple script to launch the daemon, for example:
https://github.com/rockchip-linux/meta-rockchip/blob/yocto-next/recipes-multimedia/rockchip-rkisp/rockchip-rkisp.bb
https://github.com/rockchip-linux/meta-rockchip/blob/yocto-next/recipes-multimedia/rockchip-rkisp/files/rkisp_daemons.sh


BTW, the readme and documents can be found in the https://github.com/rockchip-linux/docs i guess.
