### ISSUE TITLE
RKIQTool

### ISSUE THREAD

**Issue by kadirbeytorun** [rockchip-linux/camera_engine_rkisp#7]
Hello  @JeffyCN ,

I know you don't manage this repository, yet it seems you are the only one from Rockchips development team that responds properly to our questions so I disturb you again since we couldn't get a proper reply from "Kever" in your team via email.
 
While searching for rkisp parameter tuning (iqfile adjusting), we came across this documentation about "RKIQTool". It seems to be a windows application developed by rockchip to adjust isp parameters in a visualized way, yet we cannot figure out where to get this application, nor how we can get authorization to log in to use it.
 
Could you shed some light on the matter?

We found "RKIQTool" mentioned only on khadas forums as shown below:
https://forum.khadas.com/t/xml-camera-profile/4756
 
Kind Regards

**Comment by JeffyCN** [comment]
Well, i know nothing about this tool(likely so does Kever). Most of RK guys are not aware of github issues, we are using our redmine issue system.

Anyway, if you want support for the tool, maybe try to check related git logs, and mail the commiters who might know it.

My guess would be:
zhengsq@rock-chips.com
zyc@rock-chips.com
zack.zeng@rock-chips.com

**Comment by kadirbeytorun** [comment]
Yeah I noticed most developers don't really check their repositories on github. Is redmine rockchip's original git repository system? Or just a bug report and support system, like a forum site?

Thank you for your speedy reply by the way Jeffy. I emailed them now, hopefully they will give us some support.
